#pragma once

#define INSTANTOS_SYS_EXIT 2
#define INSTANTOS_SYS_WRITE 3
#define INSTANTOS_SYS_READ 4
#define INSTANTOS_SYS_OPEN 5
#define INSTANTOS_SYS_CLOSE 6
#define INSTANTOS_SYS_GETPID 7
#define INSTANTOS_SYS_MMAP 12
#define INSTANTOS_SYS_MUNMAP 13
#define INSTANTOS_SYS_YIELD 14
#define INSTANTOS_SYS_SLEEP 15
#define INSTANTOS_SYS_GETTIME 16
#define INSTANTOS_SYS_SET_THREAD_POINTER 118
